rails-address-book/config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

rails-address-book/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails-address-book/app/models/contact.rb
class Contact < ApplicationRecord
  validates :last_name, presence: true

  def full_name
    return last_name if first_name.blank?

    "#{first_name} #{last_name}"
  end
end

rails-address-book/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails-address-book/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  def show
    @contacts = Contact.all
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact, notice: "Contact was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /contacts/1
  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: "Contact was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /contacts/1
  def destroy
    @contact.destroy!
    redirect_to contacts_url, notice: "Contact was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :birthday)
    end
end

rails-address-book/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

rails-address-book/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-address-book/app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>First name:</strong>
    <%= contact.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= contact.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= contact.birthday %>
  </p>

</div>

rails-address-book/app/views/contacts/_details.html.erb
<%= turbo_frame_tag :contact_details do %>
  <div class="details">
    <h1><%= contact.full_name %></h1>
    <p><%= contact.email %></p>
    <p><%= contact.phone %></p>
    <p><%= contact.birthday %></p>
    <%= link_to edit_contact_path(contact) do %>
      <span class="visually-hidden">Edit</span>
      <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to contact_path(contact), data: { turbo_method: :delete, turbo_frame: '_top' } do %>
      <span class="visually-hidden">Delete</span>
      <i class="fas fa-trash"></i>
    <% end %>
  </div>
<% end %>

rails-address-book/app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :birthday %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

rails-address-book/app/views/contacts/_list.html.erb
<div class="list-group" data-controller='active'>
  <% contacts.each do |contact| %>
    <%= link_to contact.full_name, contact, class: "list-group-item list-group-item-action #{'active' if contact == selected_contact}", data: { turbo_frame: :contact_details, turbo_action: :advance, action: "click->active#activate" }%>
  <% end %>
</div>

rails-address-book/app/views/contacts/edit.html.erb
<%= turbo_frame_tag :contact_details do %>
  <h1>Editing contact</h1>
  <%= render "form", contact: @contact %>
  <br>
  <div>
    <%= link_to "Back to this contact", contact_path(@contact) %>
  </div>
<% end %>

rails-address-book/app/views/contacts/index.html.erb
<div class="contacts-grid">
  <%= render 'contacts/list', contacts: @contacts, selected_contact: nil %>
  <div class="text-secondary">Select a contact to view details</div>
</div>

rails-address-book/app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

rails-address-book/app/views/contacts/show.html.erb
<div class="contacts-grid">
  <%= render 'contacts/list', contacts: @contacts, selected_contact: @contact %>
  <%= render 'contacts/details', contact: @contact %>
</div>

rails-address-book/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAddressBook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails-address-book/app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>