gardens-and-plants/config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: [:create]
  end

  resources :plants, only: [:destroy]
end

gardens-and-plants/app/models/garden.rb
class Garden < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true

  has_many :plants, dependent: :destroy
end

gardens-and-plants/app/models/plant.rb
class Plant < ApplicationRecord
  validates :name, presence: true
  validates :image_url, presence: true

  belongs_to :garden
end

gardens-and-plants/app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[ show edit update destroy ]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    # Prepare an empty Plant instance to display the form
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: "Garden was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: "Garden was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: "Garden was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_garden
    @garden = Garden.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def garden_params
    params.require(:garden).permit(:name, :banner_url)
  end
end

gardens-and-plants/app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    # Find the garden
    @garden = Garden.find(params[:garden_id])
    # Instantiate a plant with strong params
    @plant = Plant.new(plant_params)
    # Assign the garden to the plant
    @plant.garden = @garden
    # Save

    if @plant.save
      redirect_to garden_path(@garden)
    else
      # render
      render 'gardens/show', status: :unprocessable_entity

      # We need to specify that we want the show.html.erb under gardens folder to render.
      # It is because by default, when you say render :show, Rails would try to find a file
      # that has the name `show` inside the `plants` folder, because we are in PlantsController
    end
  end

  def destroy
    # Finding the plant
    @plant = Plant.find(params[:id])
    # Destroy
    @plant.destroy
    # Redirect the user
    redirect_to garden_path(@plant.garden), status: :see_other
  end

  private

   def plant_params
    params.require(:plant).permit(:name, :image_url)
   end
end

gardens-and-plants/app/helpers/gardens_helper.rb
module GardensHelper
end

gardens-and-plants/app/helpers/plants_helper.rb
module PlantsHelper
end

gardens-and-plants/app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

gardens-and-plants/app/views/gardens/_garden.html.erb
<div id="<%= dom_id garden %>">
  <p>
    <strong>Name:</strong>
    <%= garden.name %>
  </p>

  <p>
    <strong>Banner url:</strong>
    <%= garden.banner_url %>
  </p>

</div>

gardens-and-plants/app/views/gardens/edit.html.erb
<h1>Editing garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Show this garden", @garden %> |
  <%= link_to "Back to gardens", gardens_path %>
</div>

gardens-and-plants/app/views/gardens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gardens</h1>

<div id="gardens">
  <% @gardens.each do |garden| %>
    <%= render garden %>
    <p>
      <%= link_to "Show this garden", garden %>
    </p>
  <% end %>
</div>

<%= link_to "New garden", new_garden_path %>

gardens-and-plants/app/views/gardens/new.html.erb
<h1>New garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Back to gardens", gardens_path %>
</div>

gardens-and-plants/app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>
<!-- Display cards of plants we have -->
<div class="container mt-3">
  <div class="row gx-5">
    <% @garden.plants.each do |plant| %>
      <div class="col-4">
        <div class="card">
          <img src="<%= plant.image_url%>" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title"><%= plant.name %></h5>
            <%= link_to 'Delete', plant_path(plant), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: 'Sure?' }  %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <%= simple_form_for [@garden, @plant] do |f| %>
      <%= f.input :name %>
      <%= f.input :image_url %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

gardens-and-plants/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>